// styles.js — Extracted from InventoryPanel.jsx
import { COLORS } from './constants';

// ── Estilos base reutilizables ─────────────────────────────
export const S = {
  font: { fontFamily: "'IBM Plex Mono', monospace" },
  label: {
    fontFamily: "'IBM Plex Mono', monospace",
    fontSize: 9,
    fontWeight: 700,
    textTransform: 'uppercase',
    letterSpacing: '1.5px',
    color: COLORS.gray,
    marginBottom: 2,
  },
  input: {
    fontFamily: "'IBM Plex Mono', monospace",
    fontSize: 12,
    border: `2px solid ${COLORS.black}`,
    borderRadius: 0,
    padding: '6px 8px',
    background: COLORS.white,
    outline: 'none',
    width: '100%',
    boxSizing: 'border-box',
  },
  select: {
    fontFamily: "'IBM Plex Mono', monospace",
    fontSize: 12,
    border: `2px solid ${COLORS.black}`,
    borderRadius: 0,
    padding: '6px 8px',
    background: COLORS.white,
    outline: 'none',
    width: '100%',
    boxSizing: 'border-box',
    cursor: 'pointer',
  },
  btnPrimary: {
    fontFamily: "'IBM Plex Mono', monospace",
    fontSize: 11,
    fontWeight: 700,
    textTransform: 'uppercase',
    letterSpacing: '1px',
    border: `2px solid ${COLORS.black}`,
    borderRadius: 0,
    padding: '8px 16px',
    background: COLORS.black,
    color: COLORS.white,
    cursor: 'pointer',
    boxShadow: `3px 3px 0 ${COLORS.black}`,
    transition: 'all 0.15s ease',
  },
  btnSecondary: {
    fontFamily: "'IBM Plex Mono', monospace",
    fontSize: 10,
    fontWeight: 700,
    textTransform: 'uppercase',
    letterSpacing: '1px',
    border: `2px solid ${COLORS.black}`,
    borderRadius: 0,
    padding: '6px 12px',
    background: COLORS.white,
    color: COLORS.black,
    cursor: 'pointer',
    transition: 'all 0.15s ease',
  },
  chip: (bg, color = COLORS.black) => ({
    fontFamily: "'IBM Plex Mono', monospace",
    fontSize: 10,
    fontWeight: 700,
    padding: '2px 8px',
    border: `2px solid ${COLORS.black}`,
    borderRadius: 0,
    background: bg,
    color,
    display: 'inline-block',
    lineHeight: '16px',
  }),
};
